from Libraries.Data import vgsales_original_df

import streamlit as st

st.set_page_config(
    page_title="Introduction - Projet jeux vidéo",
    layout="wide",
    menu_items={}
)

st.markdown("""
        <style>
               .block-container {
                    padding-top: 1rem;
                    padding-bottom: 2rem;
                    padding-left: 5rem;
                    padding-right: 5rem;
                }
        </style>
        """, unsafe_allow_html=True)

st.image("Images/pixel_art.jpg")
st.title("Introduction: Analyse des ventes de jeux vidéo")
st.markdown("""
## **Description du projet:**

Estimer les ventes totales d’un jeu vidéo à l’aide d’informations descriptives comme:
* Le pays d’origine
* Le studio l’ayant développé
* L’éditeur l’ayant publié
* La description du jeu
* La plateforme sur laquelle le jeu est sortie
* Le genre

Les données de base proviennent du site https://www.kaggle.com/datasets/gregorut/videogamesales

Les autres descripteurs devront être récupérés via du web scraping à l’aide de la libraire BeautifulSoup (par exemple).
""")

with st.expander("Metadata provenant de la page Kaggle", expanded=False, icon=None):
    st.markdown("""
This dataset contains a list of video games with sales greater than 100,000 copies. It was generated by a scrape of vgchartz.com.

Fields include:

* Rank - Ranking of overall sales
* Name - The games name
* Platform - Platform of the games release (i.e. PC,PS4, etc.)
* Year - Year of the game's release
* Genre - Genre of the game
* Publisher - Publisher of the game
* NA_Sales - Sales in North America (in millions)
* EU_Sales - Sales in Europe (in millions)
* JP_Sales - Sales in Japan (in millions)
* Other_Sales - Sales in the rest of the world (in millions)
* Global_Sales - Total worldwide sales.

The script to scrape the data is available at https://github.com/GregorUT/vgchartzScrape.
It is based on BeautifulSoup using Python.
There are 16,598 records. 2 records were dropped due to incomplete information.
""")


st.dataframe(vgsales_original_df.head(10))
shape = vgsales_original_df.shape
st.write(f"Dimensions du jeu de données: {shape[0]} lignes pour {shape[1]} colonnes")

